"""empty message

Revision ID: 99d19ccc5b06
Revises: 
Create Date: 2019-11-19 16:04:38.604741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d19ccc5b06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'order_id')
    op.add_column('review', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'review', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'product_id')
    op.drop_column('review', 'customer_id')
    op.add_column('product', sa.Column('order_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'product', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'product_id')
    # ### end Alembic commands ###
